/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package value_resistor;

import java.awt.Color;

/**
 *
 * @author RFauziSiregar
 */
public class GUI_Value extends javax.swing.JFrame {
    
    //Declare RGB Value in Decimal
    private static final Color BLACK = new Color(0,0,0);
    private static final Color BROWN = new Color(165,42,42);
    private static final Color RED = new Color(255,0,0);
    private static final Color ORANGE = new Color(255,165,0);
    private static final Color YELLOW = new Color(255,255,0);
    private static final Color GREEN = new Color(0,128,0);
    private static final Color BLUE = new Color(0,0,255);
    private static final Color PURPLE = new Color(128,0,128);
    private static final Color GRAY = new Color(128,128,128);
    private static final Color WHITE = new Color(255,255,255);
    private static final Color GOLD = new Color(212,175,55);
    private static final Color SILVER = new Color(192,192,192);
    private static final Color NONE = new Color(255,228,181);
    

    /**
     * Creates new form GUI_Value
     */
    public GUI_Value() {
        initComponents();
        setTitle("Resistor Calculator");
        Band1.setBackground(NONE);
        Band2.setBackground(NONE);
        Band3.setBackground(NONE);
        Band4.setBackground(NONE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblColor = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        cmbNumber = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbMulti = new javax.swing.JComboBox<>();
        lblMulti = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbTolerance = new javax.swing.JComboBox<>();
        lblTolerance = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Band1 = new javax.swing.JButton();
        Band2 = new javax.swing.JButton();
        Band3 = new javax.swing.JButton();
        Band4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        txtHasil2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHasil1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTol.setBackground(new java.awt.Color(204, 204, 204));
        lblTol.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(lblTol, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 249, 50, 20));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblColor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(0, 0, 0));
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Value", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 95, 45));

        cmbColor.setBackground(java.awt.Color.magenta);
        cmbColor.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cmbColor.setForeground(new java.awt.Color(0, 0, 0));
        cmbColor.setMaximumRowCount(13);
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLACK", "BROWN", "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "GRAY", "WHITE" }));
        cmbColor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbColor.setFocusable(false);
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });
        jPanel2.add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 95, 34));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Colour");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BAND 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Value", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(lblNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 96, 45));

        cmbNumber.setBackground(java.awt.Color.magenta);
        cmbNumber.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cmbNumber.setForeground(new java.awt.Color(0, 0, 0));
        cmbNumber.setMaximumRowCount(13);
        cmbNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLACK", "BROWN", "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "GRAY", "WHITE" }));
        cmbNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbNumber.setFocusable(false);
        cmbNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNumberActionPerformed(evt);
            }
        });
        jPanel2.add(cmbNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 96, 34));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BAND 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("BAND 3");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Multiplier");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        cmbMulti.setBackground(java.awt.Color.magenta);
        cmbMulti.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cmbMulti.setForeground(new java.awt.Color(0, 0, 0));
        cmbMulti.setMaximumRowCount(13);
        cmbMulti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLACK", "BROWN", "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "GRAY", "WHITE", "GOLD", "SILVER" }));
        cmbMulti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbMulti.setFocusable(false);
        cmbMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMultiActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 96, 34));

        lblMulti.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMulti.setForeground(new java.awt.Color(0, 0, 0));
        lblMulti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMulti.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Value", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(lblMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 96, 45));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BAND 4");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TOLERANCE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        cmbTolerance.setBackground(java.awt.Color.magenta);
        cmbTolerance.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cmbTolerance.setForeground(new java.awt.Color(0, 0, 0));
        cmbTolerance.setMaximumRowCount(13);
        cmbTolerance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BROWN", "RED", "GREEN", "BLUE", "PURPLE", "GRAY", "GOLD", "SILVER" }));
        cmbTolerance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbTolerance.setFocusable(false);
        cmbTolerance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbToleranceActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTolerance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 96, 34));

        lblTolerance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTolerance.setForeground(new java.awt.Color(0, 0, 0));
        lblTolerance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTolerance.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Value", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(lblTolerance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 96, 45));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Band1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Band1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 20, 60));

        Band2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Band2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 20, 60));

        Band3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Band3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 20, 60));

        Band4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Band4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 20, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resistor.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 80));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 231, 130));

        btnExit.setBackground(java.awt.Color.magenta);
        btnExit.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 120, 40));

        btnCal.setBackground(java.awt.Color.magenta);
        btnCal.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnCal.setForeground(new java.awt.Color(0, 0, 0));
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        jPanel2.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, 40));

        txtHasil2.setBackground(new java.awt.Color(255, 255, 255));
        txtHasil2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtHasil2.setForeground(new java.awt.Color(0, 0, 0));
        txtHasil2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtHasil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 182, 38));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("OR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        txtHasil1.setBackground(new java.awt.Color(255, 255, 255));
        txtHasil1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtHasil1.setForeground(new java.awt.Color(0, 0, 0));
        txtHasil1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtHasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 182, 38));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("value of resistor :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
        if(cmbColor.getSelectedIndex()==0){
            lblColor.setText("0");
            Band1.setBackground(BLACK);
        }
        else if(cmbColor.getSelectedIndex()==1){
            lblColor.setText("1");
            Band1.setBackground(BROWN);
        }
        else if(cmbColor.getSelectedIndex()==2){
            lblColor.setText("2");
            Band1.setBackground(RED);
        }
        else if(cmbColor.getSelectedIndex()==3){
            lblColor.setText("3");
            Band1.setBackground(ORANGE);
        }
        else if(cmbColor.getSelectedIndex()==4){
            lblColor.setText("4");
            Band1.setBackground(YELLOW);
        }
        else if(cmbColor.getSelectedIndex()==5){
            lblColor.setText("5");
            Band1.setBackground(GREEN);
        }
        else if(cmbColor.getSelectedIndex()==6){
            lblColor.setText("6");
            Band1.setBackground(BLUE);
        }
        else if(cmbColor.getSelectedIndex()==7){
            lblColor.setText("7");
            Band1.setBackground(PURPLE);
        }
        else if(cmbColor.getSelectedIndex()==8){
            lblColor.setText("8");
            Band1.setBackground(GRAY);
        }
        else if(cmbColor.getSelectedIndex()==9){
            lblColor.setText("9");
            Band1.setBackground(WHITE);
        }
    }//GEN-LAST:event_cmbColorActionPerformed

    private void cmbNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNumberActionPerformed
        // TODO add your handling code here:
        if(cmbNumber.getSelectedIndex()==0){
            lblNumber.setText("0");
            Band2.setBackground(BLACK);
        }
        else if(cmbNumber.getSelectedIndex()==1){
            lblNumber.setText("1");
            Band2.setBackground(BROWN);
        }
        else if(cmbNumber.getSelectedIndex()==2){
            lblNumber.setText("2");
            Band2.setBackground(RED);
        }
        else if(cmbNumber.getSelectedIndex()==3){
            lblNumber.setText("3");
            Band2.setBackground(ORANGE);
        }
        else if(cmbNumber.getSelectedIndex()==4){
            lblNumber.setText("4");
            Band2.setBackground(YELLOW);
        }
        else if(cmbNumber.getSelectedIndex()==5){
            lblNumber.setText("5");
            Band2.setBackground(GREEN);
        }
        else if(cmbNumber.getSelectedIndex()==6){
            lblNumber.setText("6");
            Band2.setBackground(BLUE);
        }
        else if(cmbNumber.getSelectedIndex()==7){
            lblNumber.setText("7");
            Band2.setBackground(PURPLE);
        }
        else if(cmbNumber.getSelectedIndex()==8){
            lblNumber.setText("8");
            Band2.setBackground(GRAY);
        }
        else if(cmbNumber.getSelectedIndex()==9){
            lblNumber.setText("9");
            Band2.setBackground(WHITE);
        }
    }//GEN-LAST:event_cmbNumberActionPerformed

    private void cmbMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMultiActionPerformed
        // TODO add your handling code here:
        if(cmbMulti.getSelectedIndex()==0){
            lblMulti.setText("1");
            Band3.setBackground(BLACK);
        }
        else if(cmbMulti.getSelectedIndex()==1){
            lblMulti.setText("10");
            Band3.setBackground(BROWN);
        }
        else if(cmbMulti.getSelectedIndex()==2){
            lblMulti.setText("100");
            Band3.setBackground(RED);
        }
        else if(cmbMulti.getSelectedIndex()==3){
            lblMulti.setText("1000");
            Band3.setBackground(ORANGE);
        }
        else if(cmbMulti.getSelectedIndex()==4){
            lblMulti.setText("10000");
            Band3.setBackground(YELLOW);
        }
        else if(cmbMulti.getSelectedIndex()==5){
            lblMulti.setText("100000");
            Band3.setBackground(GREEN);
        }
        else if(cmbMulti.getSelectedIndex()==6){
            lblMulti.setText("1000000");
            Band3.setBackground(BLUE);
        }
        else if(cmbMulti.getSelectedIndex()==7){
            lblMulti.setText("10000000");
            Band3.setBackground(PURPLE);
        }
        else if(cmbMulti.getSelectedIndex()==8){
            lblMulti.setText("100000000");
            Band3.setBackground(GRAY);
        }
        else if(cmbMulti.getSelectedIndex()==9){
            lblMulti.setText("1000000000");
            Band3.setBackground(WHITE);
        }
        else if(cmbMulti.getSelectedIndex()==10){
            lblMulti.setText("0.1");
            Band3.setBackground(GOLD);
        }
        else if(cmbMulti.getSelectedIndex()==11){
            lblMulti.setText("0.01");
            Band3.setBackground(SILVER);
        }
    }//GEN-LAST:event_cmbMultiActionPerformed

    private void cmbToleranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbToleranceActionPerformed
        // TODO add your handling code here:
        if(cmbTolerance.getSelectedIndex()==0){
            String coklat ="\u00B1 1%";
            String toUpperCase = coklat.toUpperCase();
            lblTolerance.setText(coklat);
            lblTol.setText("0.01");
            Band4.setBackground(BROWN);
        }
        else if(cmbTolerance.getSelectedIndex()==1){
            String merah ="\u00B1 2%";
            String toUpperCase = merah.toUpperCase();
            lblTolerance.setText(merah);
            lblTol.setText("0.02");
            Band4.setBackground(RED);
        }
        else if(cmbTolerance.getSelectedIndex()==2){
            String hijau ="\u00B1 0.5%";
            String toUpperCase = hijau.toUpperCase();
            lblTolerance.setText(hijau);
            lblTol.setText("0.005");
            Band4.setBackground(GREEN);
        }
        else if(cmbTolerance.getSelectedIndex()==3){
            String biru ="\u00B1 0.25%";
            String toUpperCase = biru.toUpperCase();
            lblTolerance.setText(biru);
            lblTol.setText("0.0025");
            Band4.setBackground(BLUE);
        }
        else if(cmbTolerance.getSelectedIndex()==4){
            String ungu ="\u00B1 0.10%";
            String toUpperCase = ungu.toUpperCase();
            lblTolerance.setText(ungu);
            lblTol.setText("0.001");
            Band4.setBackground(PURPLE);
        }
        else if(cmbTolerance.getSelectedIndex()==5){
            String abu ="\u00B1 0.05%";
            String toUpperCase = abu.toUpperCase();
            lblTolerance.setText(abu);
            lblTol.setText("0.0005");
            Band4.setBackground(GRAY);
        }
        else if(cmbTolerance.getSelectedIndex()==6){
            String emas ="\u00B1 5%";
            String toUpperCase = emas.toUpperCase();
            lblTolerance.setText(emas);
            lblTol.setText("0.05");
            Band4.setBackground(GOLD);
        }
        else if(cmbTolerance.getSelectedIndex()==7){
            String perak ="\u00B1 10%";
            String toUpperCase = perak.toUpperCase();
            lblTolerance.setText(perak);
            lblTol.setText("0.1");
            Band4.setBackground(SILVER);
        }
    }//GEN-LAST:event_cmbToleranceActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        //Declare Variable and Change Value of String to Double and int
        int [] x = new int[8];
        double [] z = new double[8];
        String c = String.format(lblColor.getText());
        String n = String.format(lblNumber.getText());
        String com = c + n;
        x[1] = Integer.parseInt(com);
        x[2] = x[1];
        z[1] = Double.parseDouble(com);
        z[2] = z[1];
        
        //Unicode for symbol Ohm
        String simbol1 = ("\u2126");
        String simbol2 = ("K\u2126");
        String simbol3 = ("M\u2126");
        
        //Hasil 1
        double time = Double.parseDouble(lblMulti.getText());
        double hitung1 = ((z[2]) * time);
        
        //Hasil 2
        double persen = Double.parseDouble(lblTol.getText());
        double koma = ((z[2]) * time) * persen;
        double minus = ((z[2]) * time) - koma;
        double plus = ((z[2]) * time) + koma;
        
        if(hitung1 >= 0 && hitung1 <= 999){
            //Hasil 1
            String ohm = (String.format(((z[2]) * time) + simbol1));
            String hasil1 = ohm + (" ") + lblTolerance.getText();
            txtHasil1.setText(hasil1);
            
            //Hasil2
            String hasilminus = (String.format(minus + simbol1));
            String hasilplus =  (String.format(plus + simbol1));
            String hasil2 = hasilminus + (" ") + ("to") + (" ") + hasilplus;
            txtHasil2.setText(hasil2);
            
        }
        else if(hitung1 >= 1000 && hitung1 <= 999999){
            //Hasil1
            String ohm = (String.format((((z[2]) * time) / 1000) + simbol2));
            String hasil1 = ohm + (" ") + lblTolerance.getText();
            txtHasil1.setText(hasil1);
            
            //Hasil2
            String hasilminus = (String.format((minus / 1000) + simbol2));
            String hasilplus =  (String.format((plus / 1000) + simbol2));
            String hasil2 = hasilminus + (" ") + ("to") + (" ") + hasilplus;
            txtHasil2.setText(hasil2);
        }
        else{
            //Hasil1
            String ohm = (String.format((((z[2]) * time) / 1000000) + simbol3));
            String hasil1 = ohm + (" ") + lblTolerance.getText();
            txtHasil1.setText(hasil1);
            
            //Hasil2
            String hasilminus = (String.format((minus / 1000000) + simbol3));
            String hasilplus =  (String.format((plus / 1000000) + simbol3));
            String hasil2 = hasilminus + (" ") + ("to") + (" ") + hasilplus;
            txtHasil2.setText(hasil2);
        }
            
        
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Value().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Band1;
    private javax.swing.JButton Band2;
    private javax.swing.JButton Band3;
    private javax.swing.JButton Band4;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbMulti;
    private javax.swing.JComboBox<String> cmbNumber;
    private javax.swing.JComboBox<String> cmbTolerance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMulti;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblTol;
    private javax.swing.JLabel lblTolerance;
    private javax.swing.JTextField txtHasil1;
    private javax.swing.JTextField txtHasil2;
    // End of variables declaration//GEN-END:variables
}
